displayName: Request Timeout
type: middleware

import: github.com/AlexRoman/traefikpluginrequesttimeout

summary: 'Add a timeout to a request'

testData:
  traefikpluginrequesttimeout:
    responseTimeout: 15s
